dochuber:           # Секция конфигурирования AI-ассистента
  contexts:         # Конфигурации контекстов
    global:         
      # Генератор глобального контекта. Информация будет добавляться во все запросы.
      # Каждый генератор верхнего уровня должен иметь идентификатор
      dochub.statistic.docs:  
        source: >             # Генерируем информацию с использование JSONata о количестве документов в репозитории
          (
            "Всего документов в текущем репозитории: " & $count(docs.*) & "шт"
          )
      # Пример интеграции с внешним ресурсом
      dochub.integrations.weather:
        # Тип генератора указываем явно 
        type: resource
        # Ссылка на внешний ресурс, который в формате RSS возвращает информацию о погоде
        # Используем сервис allorigins.win для решения проблемы CORS
        source: https://api.allorigins.win/raw?url=http://news.hmn.ru/news_out/xml/news_rss.xml
      # Пример генерации правила
      dochub.rules.techstack:
        # Тип генератора указываем явно 
        type: dataset
        # Декларируем правило использования техстека
        source: > 
          (
            "При описании архитектурных компонентов (components) требуется использовать следующий технологический стек: "
            & ($distinct(components.*.technologies)~>$join(' ;')) & ". "
            & "Этот технологический стек актуален для всего репозитория. "
            & "Если в архитектурном компоненте будет обнаружена технология не входящая в этот список, требуется об этом сообщить пользователю."
          )
      # Пример генерации контекста на основе пакета документов
      dochub.metamodel:
        # Тип генератора указываем явно
        type: generator
        # Готовим массив генераторов
        source: >
          (
            /* Перебираем все документы */
            docs.$spread().(
              /* Получаем идентификатор документа */
              $key := $keys()[0];
              /* Если идентификатор относится к документации по метамодели сключаем его в выборку */
              $key~>$substring(0, 22) = "dochub.flex_metamodel." 
                /* Создаем генератор */
                ? {
                  "type": "resource",                   /* Используем тип "resource" для ссылки на документ */
                  "$base": "/docs/" & $key & "/source", /* Используем "магическое" свойство указывающее от какого пути в Datalake разрешать ссылки на файлы */
                  "source": *.source                    /* Получаем ссылку на файл */
                }
            )
          )
        