dochuber:           # Секция конфигурирования AI-ассистента
  contexts:         # Конфигурации контекстов
    global:         # Глобальный контекст. Информация будет добавляться во все запросы.
      dochub.statistic.docs:  # Идентификатор генератора контекста
        source: >             # Генерируем информацию с использование JSONata о количестве документов в репозитории
          (
            "Всего документов в текущем репозитории: " & $count(docs.*) & "шт"
          )